{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eck-exporter.fullname" . }}
  labels:
    {{- include "eck-exporter.labels" . | nindent 4 }}
    {{- with .Values.service.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
  - name: metrics
    port: {{ .Values.service.port | int }}
    targetPort: metrics
  selector:
    {{- include "eck-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
