---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-packetloss-exporter.serviceAccountName" . }}-config-reloader
subjects:
- kind: ServiceAccount
  name: {{ include "kube-packetloss-exporter.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kube-packetloss-exporter.serviceAccountName" . }}-config-reloader
  apiGroup: rbac.authorization.k8s.io
