{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-packetloss-exporter.fullname" . }}
  labels:
    {{- include "kube-packetloss-exporter.labels" . | nindent 4 }}
  {{ with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  selector:
    {{- include "kube-packetloss-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
