{{- if or .Values.controlPlane.enabled }}
{{- if or .Values.kubeControllerManager.enabled .Values.kubeScheduler.enabled .Values.etcd.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "monitoring-proxy.fullname" . }}
  labels:
    {{- include "monitoring-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  selector:
    matchLabels:
      {{- include "monitoring-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monitoring-proxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: control-plane
    spec:
      serviceAccountName: {{ include "monitoring-proxy.serviceAccountName" . }}
      hostNetwork: true
      {{- if or .Values.kubeControllerManager.enabled .Values.kubeScheduler.enabled }}
      volumes:
        - name: config-haproxy
          configMap:
            name: {{ include "monitoring-proxy.fullname" . }}-haproxy
      {{- end }}
      nodeSelector:
        {{- if .Values.controlPlane.overrideNodeSelector }}
          {{- toYaml .Values.controlPlane.overrideNodeSelector | nindent 8 }}
        {{- else }}
          {{- toYaml .Values.controlPlane.nodeSelector | nindent 8 }}
        {{- end }}
      tolerations:
        {{- toYaml .Values.controlPlane.tolerations | nindent 8 }}
      {{- with default .Values.priorityClassName .Values.controlPlane.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
      {{- if or .Values.kubeControllerManager.enabled .Values.kubeScheduler.enabled }}
        - name: haproxy
          image: {{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}
          volumeMounts:
            - name: config-haproxy
              mountPath: /usr/local/etc/haproxy
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.kubeControllerManager.port }}
              name: kube-c-m
            - containerPort: {{ .Values.kubeScheduler.port }}
              name: kube-scheduler
          securityContext:
            allowPrivilegeEscalation: false
      {{- else }}
      {{- if .Values.controlPlane.service.enabled }}
        - name: placeholder
          image: registry.k8s.io/pause
          ports:
            - containerPort: {{ .Values.kubeControllerManager.port }}
              name: kube-c-m
            - containerPort: {{ .Values.kubeScheduler.port }}
              name: kube-scheduler
      {{- end }}
      {{- end }}
      {{- if .Values.etcd.enabled }}
        - name: kube-rbac-proxy
          image: {{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}
          args:
            {{- if .Values.etcd.https }}
            - "--secure-listen-address=$(POD_IP):{{ .Values.etcd.port }}"
            {{- else }}
            - "--insecure-listen-address=$(POD_IP):{{ .Values.etcd.port }}"
            {{- end }}
            - "--upstream={{ .Values.etcd.upstreamScheme }}://127.0.0.1:{{ .Values.etcd.port }}/"
            - "--auth-header-fields-enabled"
            - "--allow-paths=/metrics"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.kubeRbacProxy.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.etcd.port }}
              name: etcd
          securityContext:
            allowPrivilegeEscalation: false
      {{- else }}
      {{- if .Values.controlPlane.service.enabled }}
        - name: placeholder-etcd
          image: registry.k8s.io/pause
          ports:
            - containerPort: {{ .Values.etcd.port }}
              name: etcd
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
