{{- if .Values.customServices.ro.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.customServices.ro.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "cnpg-cluster.fullname" . }}-custom-ro
spec:
  type: {{ .Values.customServices.ro.type }}
  internalTrafficPolicy: Cluster
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: {{ include "cnpg-cluster.fullname" . }}
    role: replica
  {{- with .Values.customServices.ro.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}