apiVersion: v1
kind: Service
metadata:
  {{- with .Values.customServices.r.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "cnpg-cluster.fullname" . }}-custom-r
spec:
  type: {{ .Values.customServices.r.type }}
  internalTrafficPolicy: Cluster
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: {{ include "cnpg-cluster.fullname" . }}
    cnpg.io/podRole: instance
  {{- with .Values.customServices.r.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
