apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "zfs-exporter.fullname" . }}
  labels:
    {{- include "zfs-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zfs-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zfs-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zfs-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9134
              hostPort: 9134
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: chroot-zfs
              mountPath: /sbin/zfs
              subPath: zfs
            - name: chroot-zfs
              mountPath: /sbin/zpool
              subPath: zpool
            - name: host-root
              mountPath: /host
              mountPropagation: "HostToContainer"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - configMap:
          defaultMode: 365
          name: zfspv-bin
        name: chroot-zfs
      - hostPath:
          path: /
          type: Directory
        name: host-root
